### ISSUE TITLE
Cannot import name 'Never' from 'typing'

### ISSUE THREAD

**Issue by hdemers** [ptmcg/logmerger#33]
This seems like a very interesting tool. However, I immediately get the following error upon running the CLI:
```
Traceback (most recent call last):
  File "/home/-----/.local/bin/logmerger", line 5, in <module>
    from logmerger.logmerger import main
  File "/home/------/.local/pipx/venvs/logmerger/lib/python3.10/site-packages/logmerger/logmerger.py", line 16, in <module>
    from typing import TypeVar, Never
ImportError: cannot import name 'Never' from 'typing' (/usr/lib/python3.10/typing.py)
```
This is because I'm using Python 3.10 and `Never` was [introduced in 3.11](https://docs.python.org/3/library/typing.html#typing.Never). 

Maybe specify `python_requires= >=3.11` or use `NoReturn` (my preference to the latter).

Thanks.

**Comment by ptmcg** [comment]
Nice catch, thank you! I think I'd actually like to maintain support back to 3.9, so I'll clean up a few other typing usages too.
