### ISSUE TITLE
support more timestamp formats

### ISSUE THREAD

**Issue by sebhaase** [ptmcg/logmerger#36]
I have `2023/12/03 02:30:18` in my nginx log
and   `[Fri Dec 01 00:00:25.933177 2023]` in my apache log.
Could those be support ed by default?  Or can I add support via the `--timestamp_format` option?
Otherwise, it looks like a very useful nice tool.

**Comment by ptmcg** [comment]
The nginx log timestamp looks pretty standard. Is the Apache log format also a standard/default format, or something your site has customized?

**Comment by ptmcg** [comment]
Apache log format was added in 0.10.0 - closing.
