### ISSUE TITLE
timestamp not found but in supported format

### ISSUE THREAD

**Issue by blafasel42** [ptmcg/logmerger#41]
I have log lines of the form:
INFO: 2024-05-03 08:03:10,226 argos.reboot_log update_reboot_count:75- Update reboot log time and num of reboots

and i get an error "ValueError: no match for any timestamp pattern"
The timestamp pattern is exactly the first supported one. What am i doing wrong?

**Comment by ptmcg** [comment]
The leading "INFO:" is throwing off the parsing of the timestamp, logmerger looks at each log line starting at the beginning, not using a search.

logmerger does accept custom log line formats, as long as the timestamp matches a known format (as yours does). To do that, enter this command:

```
logmerger --timestamp_format "(INFO\: )((...) )" -- working/issue_41.txt
```

There is more info in the internal help shown when you hit 'h' while viewing a log with logmerger.

**Comment by ptmcg** [comment]
Were you able to get this working for you?

**Comment by blafasel42** [comment]
yes, thank you
