### ISSUE TITLE
Option to ignore lines that don't have valid timestamp?

### ISSUE THREAD

**Issue by RTnhN** [ptmcg/logmerger#42]
I am working with some logs that have some other content sprinkled in. I would be fine with removing it though as long as it could still merge based on the lines that do have the right log format. So basically, it would be great to have an option that just ignored all invalid lines.

**Comment by ptmcg** [comment]
The non-timestamped content shouldn't _break_ the merging of the logs, it just appends the non-timestamped content as part of the most recent timestamped line.

But I have a working update that drops non-timestamped logs altogether - the switch is "--ignore_non_timestamped".  You'll be able to see it in the demo mode using "logmerger --demo --ignore_non_timestamped"

**Comment by ptmcg** [comment]
Before:
![keep_non_timestamped_merged_logs](https://github.com/user-attachments/assets/dc013d35-d532-4930-9edc-23ebdd4bbd79)

After:
![ignore_non_timestamped_merged_logs](https://github.com/user-attachments/assets/ea68617c-6798-4baf-90a9-8c1dbac1e359)

**Comment by RTnhN** [comment]
Ah, cool!

**Comment by ptmcg** [comment]
I haven't pushed a release with this yet, but you can pull it from the master branch in the repo.
